language: php
dist: trusty
sudo: false

# PHP versions to tests
php:
- 7.2
# Composer install
install:
  - travis_retry composer install --no-dev --no-interaction
# Make unit tests log directory
before_script:
  - mkdir -p build/logs
# Unit tests
script:
  - composer test
# Upload results on Coveralls
after_success:
  - sh -c 'php vendor/bin/php-coveralls -v;'