# PhpUnitGen configuration

# Erase old target files with new one
overwrite: true
# If you want to generate tests for Interface too
interface: false
# Automatically generate tests for getter / setter method
auto: true
# Ignore errors that can be ignored
ignore: false
# Regex (/.*config.php/ for example) that files must not match to have a tests generation
exclude: '/.*config.php/'
# Regex (/.*.php/ for example) that files should match to have a tests generation
include: '/.*/'
# Directories to generate tests for
dirs:
  # - source/directory: target/directory
  src/PhpUnitGen/Configuration: test/PhpUnitGen/Configuration
  src/PhpUnitGen/Model: test/PhpUnitGen/Model
  examples: test/examples